# Generated by Django 4.2 on 2023-04-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('idadmin', models.AutoField(db_column='IdAdmin', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=40)),
                ('password', models.CharField(db_column='Password', max_length=40)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Galerija',
            fields=[
                ('idslika', models.AutoField(db_column='IdSlika', primary_key=True, serialize=False)),
                ('path', models.CharField(db_column='Path', max_length=255)),
                ('tipslike', models.CharField(db_column='TipSlike', max_length=1)),
                ('idobj', models.IntegerField(blank=True, db_column='IdObj', null=True)),
                ('idvest', models.IntegerField(blank=True, db_column='IdVest', null=True)),
            ],
            options={
                'db_table': 'galerija',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iznajmljivanje',
            fields=[
                ('idizn', models.AutoField(db_column='IdIzn', primary_key=True, serialize=False)),
                ('datum', models.DateTimeField(db_column='Datum')),
                ('status', models.CharField(db_column='Status', max_length=40)),
                ('idobj', models.IntegerField(db_column='IdObj')),
                ('idrreg', models.IntegerField(db_column='IdrReg')),
            ],
            options={
                'db_table': 'iznajmljivanje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menadzer',
            fields=[
                ('idmen', models.AutoField(db_column='IdMen', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=40)),
                ('password', models.CharField(db_column='Password', max_length=40)),
                ('ime', models.CharField(db_column='Ime', max_length=40)),
                ('prezime', models.CharField(db_column='Prezime', max_length=40)),
                ('pol', models.CharField(db_column='Pol', max_length=40)),
                ('broj', models.CharField(db_column='Broj', max_length=40)),
            ],
            options={
                'db_table': 'menadzer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Objekat',
            fields=[
                ('idobj', models.AutoField(db_column='IdObj', primary_key=True, serialize=False)),
                ('naziv', models.CharField(db_column='Naziv', max_length=40)),
                ('adresa', models.CharField(db_column='Adresa', max_length=40)),
                ('grad', models.CharField(db_column='Grad', max_length=40)),
                ('tipobj', models.CharField(db_column='TipObj', max_length=40)),
                ('tipkuhinje', models.CharField(db_column='TipKuhinje', max_length=40)),
                ('ukocena', models.IntegerField(db_column='UkOcena')),
                ('brocena', models.IntegerField(db_column='BrOcena')),
                ('opis', models.CharField(db_column='Opis', max_length=1000)),
                ('idmen', models.IntegerField(db_column='IdMen')),
            ],
            options={
                'db_table': 'objekat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Omiljeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idrreg', models.IntegerField(db_column='IdrReg')),
                ('idobj', models.IntegerField(db_column='IdObj')),
            ],
            options={
                'db_table': 'omiljeni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registrovani',
            fields=[
                ('idrreg', models.AutoField(db_column='IdrReg', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=40)),
                ('password', models.CharField(db_column='Password', max_length=40)),
                ('ime', models.CharField(db_column='Ime', max_length=40)),
                ('prezime', models.CharField(db_column='Prezime', max_length=40)),
                ('brtelefona', models.CharField(db_column='BrTelefona', max_length=40)),
                ('pol', models.CharField(db_column='Pol', max_length=40)),
                ('pozpoeni', models.IntegerField(db_column='PozPoeni')),
                ('negpoeni', models.IntegerField(db_column='NegPoeni')),
                ('datumrodjenja', models.DateTimeField(db_column='DatumRodjenja')),
            ],
            options={
                'db_table': 'registrovani',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rezervacija',
            fields=[
                ('idrez', models.AutoField(db_column='IdRez', primary_key=True, serialize=False)),
                ('datum', models.DateTimeField(db_column='Datum')),
                ('status', models.CharField(db_column='Status', max_length=40)),
                ('idsto', models.IntegerField(db_column='IdSto')),
                ('idrreg', models.IntegerField(db_column='IdrReg')),
            ],
            options={
                'db_table': 'rezervacija',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sto',
            fields=[
                ('idsto', models.AutoField(db_column='IdSto', primary_key=True, serialize=False)),
                ('idobj', models.IntegerField(db_column='IdObj')),
                ('idtip', models.IntegerField(db_column='IdTip')),
            ],
            options={
                'db_table': 'sto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('idtip', models.AutoField(db_column='IdTip', primary_key=True, serialize=False)),
                ('naziv', models.CharField(db_column='Naziv', max_length=40)),
                ('opis', models.CharField(db_column='Opis', max_length=40)),
            ],
            options={
                'db_table': 'tip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vest',
            fields=[
                ('idvest', models.AutoField(db_column='IdVest', primary_key=True, serialize=False)),
                ('naslov', models.CharField(db_column='Naslov', max_length=40)),
                ('tekst', models.CharField(db_column='Tekst', max_length=255)),
            ],
            options={
                'db_table': 'vest',
                'managed': False,
            },
        ),
    ]
